# Generated by Django 4.2.7 on 2023-11-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0006_alter_book_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_biblioteca.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
